<?php /* Smarty version Smarty-3.1.12, created on 2013-07-19 20:56:35
         compiled from "module_file_tpl:Showtime;showtime_jq.tpl" */ ?>
<?php /*%%SmartyHeaderCode:66361440551e9ee53a195a6-43112278%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '854974001d330e2413bcc0cf5112ee47f978c1cd' => 
    array (
      0 => 'module_file_tpl:Showtime;showtime_jq.tpl',
      1 => 1373819437,
      2 => 'module_file_tpl',
    ),
  ),
  'nocache_hash' => '66361440551e9ee53a195a6-43112278',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'showid' => 0,
    'show' => 0,
    'items' => 0,
    'entry' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.12',
  'unifunc' => 'content_51e9ee53ae3793_54819878',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_51e9ee53ae3793_54819878')) {function content_51e9ee53ae3793_54819878($_smarty_tpl) {?><!-- generated by showtime Module start -->
        <script type="text/javascript">
        
        $(document).ready(function(){
			var lastslide=0;
			$('ul#slides_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
').cycle({ 
<?php if ($_smarty_tpl->tpl_vars['show']->value['st_showtext']||$_smarty_tpl->tpl_vars['show']->value['st_showcomment']){?>
				before: onbefore_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
,
<?php }?>
				fx: '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_transition'];?>
',
				speed:    <?php echo $_smarty_tpl->tpl_vars['show']->value['st_transitiontime'];?>
, 
				timeout:  <?php echo $_smarty_tpl->tpl_vars['show']->value['st_rotatetime'];?>
,
<?php if ($_smarty_tpl->tpl_vars['show']->value['st_navbut']){?>
				pager:   '#slideshow_nav_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
',
<?php }?> 
				pagerEvent: 'mouseover',
<?php if (!$_smarty_tpl->tpl_vars['show']->value['st_autoplay']){?>
				timeout: 0,
<?php }?>		
<?php if ($_smarty_tpl->tpl_vars['show']->value['st_shuffle']){?>
				random: 1,
<?php }?>
				fastOnEvent: false,
				pause: <?php echo $_smarty_tpl->tpl_vars['show']->value['st_pauseonhover'];?>
,
				pauseOnPagerHover: <?php echo $_smarty_tpl->tpl_vars['show']->value['st_pauseonhover'];?>
,
				prev: '#prev_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
',
				next: '#next_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
'<?php if ($_smarty_tpl->tpl_vars['show']->value['st_showtext']||$_smarty_tpl->tpl_vars['show']->value['st_showcomment']){?>,
				after: onafter_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
<?php }?> 
			});

            $("#slideshow_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
").hover(function() {
                $("ul#prevnextnav_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
").fadeIn();
            },
                function() {
                $("ul#prevnextnav_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
").fadeOut();
            });
           
        <?php if ($_smarty_tpl->tpl_vars['show']->value['st_showtext']||$_smarty_tpl->tpl_vars['show']->value['st_showcomment']){?>
            function onbefore_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
() {
                $('#com_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
_'+lastslide).clearQueue();
                $('#com_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
_'+lastslide).hide();
            }
            function onafter_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
(curr, next, opts) {
                var index = opts.currSlide;
                var indexlast = opts.lastSlide;
                $('#com_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
_'+index).queue(function (){
                    lastslide=index;
                    $(this).delay(100);
                    $(this).fadeIn(400);
                    $(this).dequeue();
                });
            }
        <?php }?>
        });

        
        </script>

        <div id="slideshow_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
" class="pics">
            <?php if ($_smarty_tpl->tpl_vars['show']->value['st_showtext']||$_smarty_tpl->tpl_vars['show']->value['st_showcomment']){?>
            <div id="comments_st_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
">
            <?php  $_smarty_tpl->tpl_vars['entry'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['entry']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['items']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['entry']->key => $_smarty_tpl->tpl_vars['entry']->value){
$_smarty_tpl->tpl_vars['entry']->_loop = true;
?>
                <div id="com_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
_<?php echo $_smarty_tpl->tpl_vars['entry']->value->slide_id;?>
" class="commentsparts_st_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
"><?php if ($_smarty_tpl->tpl_vars['show']->value['st_showtext']){?><h2><?php echo $_smarty_tpl->tpl_vars['entry']->value->picture_name;?>
</h2><?php }?><?php if ($_smarty_tpl->tpl_vars['show']->value['st_showcomment']){?><?php echo $_smarty_tpl->tpl_vars['entry']->value->comment;?>
<?php }?></div>
                <?php } ?>
            </div>
            <?php }?>
        
        <?php if ($_smarty_tpl->tpl_vars['show']->value['st_showcontrols']){?>
            <ul id="prevnextnav_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
">
                    <li id="prev_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
"><a href="#">Previous</a></li>
                    <li id="next_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
"><a href="#">Next</a></li>
            </ul>
        <?php }?>
         <?php if ($_smarty_tpl->tpl_vars['show']->value['st_navbut']){?>
            <div id="slideshow_nav_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
" class="slide_nav_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
"></div>
         <?php }?>
        
            <ul id="slides_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
">
            <?php  $_smarty_tpl->tpl_vars['entry'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['entry']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['items']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['entry']->key => $_smarty_tpl->tpl_vars['entry']->value){
$_smarty_tpl->tpl_vars['entry']->_loop = true;
?>
                <li><?php if ($_smarty_tpl->tpl_vars['entry']->value->picture_url==''){?><?php echo $_smarty_tpl->tpl_vars['entry']->value->picture;?>

                    <?php }else{ ?><a href="<?php echo $_smarty_tpl->tpl_vars['entry']->value->picture_url;?>
" target="<?php echo $_smarty_tpl->tpl_vars['entry']->value->picture_url_target;?>
"><?php echo $_smarty_tpl->tpl_vars['entry']->value->picture;?>
</a><?php }?>
                </li>
             <?php } ?>
           </ul>              
        </div> 

<!-- generated by showtime Module end -->
<?php }} ?>