<?php /* Smarty version Smarty-3.1.12, created on 2013-07-30 12:36:34
         compiled from "module_file_tpl:Showtime;showtime_swf.tpl" */ ?>
<?php /*%%SmartyHeaderCode:137980781151f7f9a2b25d10-46878701%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '9ff6cbb7e82b400d0c839a4256052c95796a552a' => 
    array (
      0 => 'module_file_tpl:Showtime;showtime_swf.tpl',
      1 => 1373819437,
      2 => 'module_file_tpl',
    ),
  ),
  'nocache_hash' => '137980781151f7f9a2b25d10-46878701',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'showid' => 0,
    'show' => 0,
    'galleryitems' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.12',
  'unifunc' => 'content_51f7f9a2b96099_67360976',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_51f7f9a2b96099_67360976')) {function content_51f7f9a2b96099_67360976($_smarty_tpl) {?><?php if (!is_callable('smarty_function_root_url')) include '/Users/darfine/Sites/barn/plugins/function.root_url.php';
?><!-- generated by showtime Module start -->
        <script type='text/javascript'>
        
            var flashvars =  { 				
            xml 			: '<?php echo smarty_function_root_url(array(),$_smarty_tpl);?>
/modules/Showtime/showtime/getxml.php?showid=<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
',
            width           : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_width'];?>
',
            height          : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_height'];?>
',
            classid         : 'st_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
',
            rotationtime    : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_rotatetime'];?>
',
            transition      : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_transition'];?>
',
            transitiontime  : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_transitiontime'];?>
',
            transitionease  : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_easeFunc'];?>
<?php echo $_smarty_tpl->tpl_vars['show']->value['st_ease'];?>
',
            autoplay        : '<?php if (($_smarty_tpl->tpl_vars['show']->value['st_autoplay'])){?>on<?php }?>',
            showcontrols    : '<?php if (($_smarty_tpl->tpl_vars['show']->value['st_showcontrols'])){?>on<?php }?>',
            controls        : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_showcontrolssub'];?>
',
            textbgcolor     : '<?php if (($_smarty_tpl->tpl_vars['show']->value['st_showalt'])){?><?php echo $_smarty_tpl->tpl_vars['show']->value['st_textbgcolor'];?>
<?php }?>',
            showtext        : '<?php if (($_smarty_tpl->tpl_vars['show']->value['st_showtext'])){?>on<?php }?>',
            showalt         : '<?php if (($_smarty_tpl->tpl_vars['show']->value['st_showcomment'])){?>on<?php }?>',
            shuffle         : '<?php if (($_smarty_tpl->tpl_vars['show']->value['st_shuffle'])){?>on<?php }?>',
            scale           : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_scale'];?>
',
            target          : '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_target'];?>
'			
             };
            
            var params = {};
            params.allowFullScreen = 'true';
            params.bgcolor = '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_bgcolor'];?>
';		
            params.quality = 'autohigh';		
            params.wmode = '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_wmode'];?>
';
            //params.wmode = 'transparent';
            //params.base = 'dirname(__FILE__)';
            //params.allowScriptAccess = 'local';
        
            var attributes = {};
            attributes.styleclass = 'showtime';
                                            
            swfobject.embedSWF ('<?php echo smarty_function_root_url(array(),$_smarty_tpl);?>
/modules/Showtime/showtime/st16.swf', 'st_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
', '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_width'];?>
', '<?php echo $_smarty_tpl->tpl_vars['show']->value['st_height'];?>
', '10.0.0', 'false', flashvars, params, attributes);
        </script>
                
        <!-- alternative content -->	
        <div id='st_<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
'>
            <div id='gallery-<?php echo $_smarty_tpl->tpl_vars['showid']->value;?>
' class='gallery'>
                <?php echo $_smarty_tpl->tpl_vars['galleryitems']->value;?>
			
                <br style='clear: both;' />
            </div>
        </div>
<!-- generated by showtime Module end --><?php }} ?>