<!-- generated by showtime Module start -->
        <script type="text/javascript">
        {literal}
		$(document).ready(function(){				
			$(window).load(function() {
                                  $('#slider{/literal}{$showid}{literal}').nivoSlider({ {/literal}
					effect: '{$show.st_transition}', // Specify sets like: 'fold,fade,sliceDown'
					slices: {$show.st_slices}, // For slice animations
					boxCols: {$show.st_box_x}, // For box animations
					boxRows: {$show.st_box_y}, // For box animations
					animSpeed: {$show.st_transitiontime}, // Slide transition speed
					pauseTime: {$show.st_rotatetime}, // How long each slide will show
					startSlide: {$show.st_start_slide}, // Set starting Slide (0 index)
					directionNav: {$show.st_showcontrols}, // Next & Prev navigation
					directionNavHide: {$show.st_controlshide}, // Only show on hover
					controlNav: {$show.st_navbut}, // 1,2,3... navigation
					controlNavThumbs: {$show.st_thumb_nav}, // Use thumbnails for Control Nav
					controlNavThumbsFromRel: true, // Use image rel for thumbs
					//controlNavThumbsSearch: '.jpg', // Replace this with...
					//controlNavThumbsReplace: '_thumb.jpg', // ...this in thumb Image src
					keyboardNav: true, // Use left & right arrows
					pauseOnHover: {$show.st_pauseonhover}, // Stop animation while hovering
					manualAdvance: {$show.st_autoplay}, // Force manual transitions
					captionOpacity: {$show.st_captionopacity}, // Universal caption opacity
					prevText: 'Prev', // Prev directionNav text
					nextText: 'Next', // Next directionNav text
					randomStart: {$show.st_shuffle}, // Start on a random slide
					{literal}
					beforeChange: function(){}, // Triggers before a slide transition
					afterChange: function(){}, // Triggers after a slide transition
					slideshowEnd: function(){}, // Triggers after all slides have been shown
					lastSlide: function(){}, // Triggers when last slide is shown
					afterLoad: function(){} // Triggers when slider has loaded				
				});
			});
		});

		{/literal}
		</script>
				
				
				
    <div class="slider-wrapper">
        <div id="slider{$showid}" class="nivoSlider">
        {foreach from=$items item=entry}
            {if $entry->picture_url == ""}
            <img src="{$entry->picture}"  alt="" title="{if ($show.st_showtext || $show.st_showcomment) && (!empty($entry->comment) || !empty($entry->picture_name)) }#htmlcaption_{$entry->picture_id}{/if}" rel="{$entry->thumbnail}"  />
            {else}
            <a href="{$entry->picture_url}" target="{$entry->picture_url_target}">
            <img src="{$entry->picture}"  alt="" title="{if $entry->comment <> ""}#htmlcaption_{$entry->picture_id}{else}{$entry->picture_name}{/if}" rel="{$entry->thumbnail}"  />
            </a>
            {/if}
        {/foreach}
        </div>
        
        {if $show.st_showtext || $show.st_showcomment}
        {foreach from=$items item=entry}
        <div id="htmlcaption_{$entry->picture_id}" class="nivo-html-caption">{if $show.st_showtext}<h2>{$entry->picture_name}</h2>{/if}{$entry->comment}
        </div>
        {/foreach}
    	{/if}
    </div>
<!-- generated by showtime Module end -->
