<!-- generated by showtime Module start -->
        <script type='text/javascript'>
        
            var flashvars = {literal} { {/literal}				
            xml 			: '{root_url}/modules/Showtime/showtime/getxml.php?showid={$showid}',
            width           : '{$show.st_width}',
            height          : '{$show.st_height}',
            classid         : 'st_{$showid}',
            rotationtime    : '{$show.st_rotatetime}',
            transition      : '{$show.st_transition}',
            transitiontime  : '{$show.st_transitiontime}',
            transitionease  : '{$show.st_easeFunc}{$show.st_ease}',
            autoplay        : '{if ($show.st_autoplay)}on{/if}',
            showcontrols    : '{if ($show.st_showcontrols)}on{/if}',
            controls        : '{$show.st_showcontrolssub}',
            textbgcolor     : '{if ($show.st_showalt)}{$show.st_textbgcolor}{/if}',
            showtext        : '{if ($show.st_showtext)}on{/if}',
            showalt         : '{if ($show.st_showcomment)}on{/if}',
            shuffle         : '{if ($show.st_shuffle)}on{/if}',
            scale           : '{$show.st_scale}',
            target          : '{$show.st_target}'			
            {literal} };
            
            var params = {};{/literal}
            params.allowFullScreen = 'true';
            params.bgcolor = '{$show.st_bgcolor}';		
            params.quality = 'autohigh';		
            params.wmode = '{$show.st_wmode}';
            //params.wmode = 'transparent';
            //params.base = 'dirname(__FILE__)';
            //params.allowScriptAccess = 'local';
        
            {literal}var attributes = {};
            attributes.styleclass = 'showtime';{/literal}
                                            
            swfobject.embedSWF ('{root_url}/modules/Showtime/showtime/st16.swf', 'st_{$showid}', '{$show.st_width}', '{$show.st_height}', '10.0.0', 'false', flashvars, params, attributes);
        </script>
                
        <!-- alternative content -->	
        <div id='st_{$showid}'>
            <div id='gallery-{$showid}' class='gallery'>
                {$galleryitems}			
                <br style='clear: both;' />
            </div>
        </div>
<!-- generated by showtime Module end -->